config/routes.rb
Rails.application.routes.draw do

  resources :comments

  get 'sessions/create'

  get 'sessions/destroy'
  get '/issues/mine', to: 'issues#mine'
  get '/issues/watching', to: 'issues#watching'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]


  root 'home#index'

  resources :issues do 
    resources :comments
    get :watchers
    member do
      put "like" => "issues#upvote"
      put "unlike" => "issues#downvote"
      put "watch" => "issues#watch"
      put "unwatch" => "issues#unwatch"
      put "edit" => "issues#edit"
    end
  end
  resources :users do
    get :watching
  end
  
  get '/issues/:id/attachment', to: 'issues#showAttachment'
  post '/issues/:id/attachment', to: 'issues#createAttachment'
  get 'Opened', to: 'issues#openIssues'
  get 'On holded', to: 'issues#onHoldIssues'  
  get 'Resolved', to: 'issues#resolveIssues'
  get 'Duplicated', to: 'issues#duplicateIssues'
  get 'Invalid', to: 'issues#invalidateIssues'
  get 'Wontfixed', to: 'issues#wontfixIssues'
  get 'Closed', to: 'issues#closeIssues'
  get 'Task', to: 'issues#taskIssues'
  get 'Bug', to: 'issues#bugIssues'
  get 'Enhancement', to: 'issues#enhancementIssues'
  get 'Proposal', to: 'issues#proposalIssues'
  get 'Trivial', to: 'issues#trivialIssues'
  get 'Minor', to: 'issues#minorIssues'
  get 'Major', to: 'issues#majorIssues'
  get 'Critical', to: 'issues#criticalIssues'
  get 'Blocker', to: 'issues#blockerIssues'
  
  post 'editcomment', controller: "issues", action: "editcomment"
  get 'destroycomment', controller: "issues" , action: "destroycomment"
  get 'openIssue', controller: "issues", action: "openIssue"
  get 'onHoldIssue', controller: "issues", action: "onHoldIssue"
  get 'resolveIssue', controller: "issues", action: "resolveIssue"
  get 'duplicateIssue', controller: "issues", action: "duplicateIssue"
  get 'invalidateIssue', controller: "issues", action: "invalidateIssue"
  get 'wontfixIssue', controller: "issues", action: "wontfixIssue"
  get 'closeIssue', controller: "issues", action: "closeIssue"
  get 'isOpen', controller: "issues", action: "isOpen"
  
end

app/models/issue.rb
class Issue < ApplicationRecord
    
    acts_as_votable
    has_many :comments, :dependent => :destroy
    has_many :passive_watches, class_name: "WatchRelationship", foreign_key: "watched_id", dependent: :destroy
    has_many :watchers, through: :passive_watches, source: :watcher
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
    #serialize :attachments, JSON
    
    def isOpened
        if self.status == "Opened"
            logger.debug "Issue is opened" 
            return true
        end
        logger.debug "Issue is not opened" 
        return false
    end
    
    def isOnHold
        if self.status == "On holded"
            logger.debug "Issue is on hold" 
            return true
        end
        logger.debug "Issue is not on hold" 
        return false
    end    
    
    def isResolved
        if self.status == "Resolved"
            logger.debug "Issue is resolved" 
            return true
        end
        logger.debug "Issue is not resolved" 
        return false
    end

    def isDuplicate
        if self.status == "Duplicated"
            logger.debug "Issue is duplicate" 
            return true
        end
        logger.debug "Issue is not duplicate" 
        return false
    end 

    def isInvalid
        if self.status == "Invalid"
            logger.debug "Issue is invalid" 
            return true
        end
        logger.debug "Issue is not invalid" 
        return false
    end
    
    def isWontfix
        if self.status == "Wontfixed"
            logger.debug "Issue is wontfix" 
            return true
        end
        logger.debug "Issue is not wontfix" 
        return false
    end    
    
    def isClosed
        if self.status == "Closed"
            logger.debug "Issue is closed" 
            return true
        end
        logger.debug "Issue is not closed" 
        return false
    end
    
    def Votes
        self.get_upvotes.size-self.get_downvotes.size
    end
    
    def getStatus
        if self.isOpened
            return "Opened"
        end
        
        if self.isOnHold
            return "On holded"
        end
        
        if self.isResolved
            return "Resolved"
        end
        
        if self.isDuplicate
            return "Duplicated"
        end
        
        if self.isInvalid
            return "Invalid"
        end
        
        if self.isWontfix
            return "Wontfixed"
        end
        
        return "Closed"
    end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy, :createAttachment, :openIssue, :onHoldIssue, :resolveIssue, :duplicateIssue, :invalidateIssue, :wontfixIssue, :closeIssue, :destroycomment, :upvote, :downvote, :download_file, :editcomment]
  helper_method :sort_column, :sort_direction

  # GET /issues
  # GET /issues.json
  def index
    respond_to do |format|
      format.html { 
        if !current_user
          redirect_to "/auth/google_oauth2" and return
        end
      }
      format.json {
        resp = authenticate
        if resp == nil
          return
        end
        #authenticateCreation
      }
    end
    @issues = Issue.all
    @given_priority = params[:priority]
    @given_status = params[:status]
    if (@given_status == "On%20holded")
      @given_status = "On holded"
    end
    @given_category = params[:category]
    error =""
    
    @issues = @issues.order(sort_column + " " + sort_direction)
    if (@given_status != nil)
      if (['Invalid', 'Duplicated','Resolved','Wontfixed','Closed','On holded','Opened'].include? @given_status )   
       @issues = @issues.where(status: @given_status).order(sort_column + " " + sort_direction)
      elsif  (@given_status != nil )  
       error = "Invalid status 4"
      end
    end
    if (@given_priority != nil)
      if (['Trivial', 'Minor','Major','Critical','Blocker'].include? @given_priority )   
       @issues = @issues.where(priority: @given_priority).order(sort_column + " " + sort_direction)
      elsif  (@given_priority != nil )  
       error = "Invalid priority 3"
      end
    end
    if (@given_category != nil)
      if (['Task', 'Bug','Proposal','Enhancement'].include? @given_category )   
       @issues = @issues.where(category: @given_category).order(sort_column + " " + sort_direction)
      elsif  (@given_category != nil )  
       error = "Invalid category 2"
      end
    end
    if !current_user
      error = "No token/invalid token"
    end
    respond_to do |format|
      if error != ""
        format.html { redirect_to @issue, notice: error }
        format.json {
          if !current_user
            render :json => {:error => error,:status => 401 }
          else
            render :json => {:error => error, :status => 400}, :status => :bad_request
          end
        }
      
      else
        format.html {
          
        }
        format.json { #es como hacer un IF
          #authenticate
          @filtraje = Array.new
          @issues.reverse_each do |var|
            @filtraje.push(var.as_json(except: [:pinnedId, :votes], methods:[:Votes] ) )
          end
          render :json => @filtraje.as_json()
  
        }
      end

    end
    
  end
  
  def decoded_auth_token
    @decoded_auth_token ||= http_auth_header
  end
  
  def http_auth_header 
    if headers['Authorization'].present? 
      return headers['Authorization'].split(' ').last 
    else 
      asdasdas # aixo fa petar xD
      errors.add(:token, 'Missing token') 
    end 
  end

  def openIssues
    logger.debug("Opened function at controller")
    @issues = Issue.where(status: 'Opened').order(sort_column + " " + sort_direction)
    respond_to do |format|
      format.html {}
      format.json { #es como hacer un IF
        render :json => @issues.as_json(except: [:pinnedId,:votes], methods:[:Votes])
      }
    end
  end
  
  def onHoldIssues
    logger.debug("Opened function at controller")
    @issues = Issue.where(status: 'On holded').order(sort_column + " " + sort_direction)
    respond_to do |format|
      format.html {}
      format.json { #es como hacer un IF
        render :json => @issues.as_json(except: [:pinnedId,:votes], methods:[:Votes])
      }
    end
  end  
  
  def resolveIssues
    logger.debug("Opened function at controller")
    @issues = Issue.where(status: 'Resolved').order(sort_column + " " + sort_direction)
    respond_to do |format|
      format.html {}
      format.json { #es como hacer un IF
        render :json => @issues.as_json(except: [:pinnedId,:votes], methods:[:Votes])
      }
    end
  end
  
  def duplicateIssues
    logger.debug("Opened function at controller")
    @issues = Issue.where(status: 'Duplicated').order(sort_column + " " + sort_direction)
    respond_to do |format|
      format.html {}
      format.json { #es como hacer un IF
        render :json => @issues.as_json(except: [:pinnedId,:votes], methods:[:Votes])
      }
    end
  end
  
  def invalidateIssues
    logger.debug("Opened function at controller")
    @issues = Issue.where(status: 'Invalid').order(sort_column + " " + sort_direction)
    respond_to do |format|
      format.html {}
      format.json { #es como hacer un IF
        render :json => @issues.as_json(except: [:pinnedId,:votes], methods:[:Votes])
      }
    end
  end
  
  def wontfixIssues
    logger.debug("Opened function at controller")
    @issues = Issue.where(status: 'Wontfixed').order(sort_column + " " + sort_direction)
    respond_to do |format|
      format.html {}
      format.json { #es como hacer un IF
        render :json => @issues.as_json(except: [:pinnedId,:votes], methods:[:Votes])
      }
    end
  end
  
  def issuesStatus
    @given_status = params[:status]
    error =""
    if (['Invalid', 'Duplicate','Resolved','Wontfix','Closed','On hold','Opened'].include? @given_status )
      error = "Invalid status"
    else
      @issues = Issue.where(status: @given_status).order(sort_column + " " + sort_direction)
    end
    
    respond_to do |format|
      if error != ""
        format.html { redirect_to @issue, notice: error }
        format.json {
           render :json => {:error => error, :status => 400}, :status => :bad_request
        }
      
      else
        format.html {}
        format.json { #es como hacer un IF
          #@user ||= User.find(decoded_auth_token[:user_id]) if decoded_auth_token
          render :json => @issues
        }
      end

    end
    
    
    
  end
  
  def closeIssues
    logger.debug("Opened function at controller")
    @issues = Issue.where(status: 'Closed').order(sort_column + " " + sort_direction)
    respond_to do |format|
      format.html {}
      format.json { #es como hacer un IF
        render :json => @issues.as_json(except: [:pinnedId,:votes], methods:[:Votes])
      }
    end
  end
  
  def mine
    respond_to do |format|
      format.html { 
        if !current_user
          redirect_to "/auth/google_oauth2" and return
        end
      }
      format.json {
        resp = authenticate
        if resp == nil
          return
        end
        authenticateCreation
      }
    end
    logger.debug("Opened function at controller")
    @issues = Issue.where(user: current_user.name).order(sort_column + " " + sort_direction)
    respond_to do |format|
      format.html {}
      format.json { #es como hacer un IF
        #authenticate
        render :json => @issues.as_json(except: [:pinnedId,:votes], methods:[:Votes])
      }
    end
  end
  
  def watching
    logger.debug("Opened function at controller")
    @issues = Issue.order(sort_column + " " + sort_direction)
    respond_to do |format|
      format.html {}
      format.json { #es como hacer un IF
        @filtraje = Array.new
        @issues.reverse_each do |var|
          if authenticate.watching?(var)  
            @filtraje.push(var.as_json(except: [:pinnedId, :votes], methods:[:Votes] ) )
          end
        end
        render :json => @filtraje.as_json()
      }
    end#de moment he fet servir la de closed per provar que funcionés
    #@issues = Issue.where(watching: true || user: current_user.nam).order(sort_column + " " + sort_direction) hauria de ser quelcom similar a aquesta
  end
  
  def taskIssues
    @issues = Issue.where(category: 'Task')
  end
  
  def bugIssues
    @issues = Issue.where(category: 'Bug')
  end
  
  def enhancementIssues
    @issues = Issue.where(category: 'Enhancement')
  end
  
  def proposalIssues
    @issues = Issue.where(category: 'Proposal')
  end
  
  def trivialIssues
    @issues = Issue.where(priority: 'Trivial')
  end
  
  def minorIssues
    @issues = Issue.where(priority: 'Minor')
  end
  
  def majorIssues
    @issues = Issue.where(priority: 'Major')
  end
  
  def criticalIssues
    @issues = Issue.where(priority: 'Critical')
  end
  
  def blockerIssues
    @issues = Issue.where(priority: 'Blocker')
  end
  
  
  def sort_column
    sortValue = params[:sort]
    if sortValue == nil
      sortValue = "created_at"
    end
    Issue.column_names.include?(sortValue) ? sortValue : sortValue
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  
  def destroycomment
    @comment=params[:comment]
    #logger.debug("destroycomment", @comment)
    @issue.comments.delete(@comment)
      redirect_to @issue, notice: 'Comment was successfully deleted.' 
    
  end
  
  def editcomment
      respond_to do |format|
      format.html { 
        if !current_user
          redirect_to "/auth/google_oauth2" and return
        end
      }
      format.json {
        resp = authenticate
        if resp == nil
          return
        end
        authenticateCreation
     #   pe=resp
     #   params[:comment][:user_id]=resp.id
      }
    end
      
    @comment = Comment.find(params[:mcomment])
    @bodyUpdate = params[:comment][:body]
    @comment.body = @bodyUpdate
    #15, :user_name => 'Samuel', :group => 'expert'
    @issue.comments.update(params[:mcomment],:body =>  @bodyUpdate)
    
      
      respond_to do |format|
      if @issue.comments.update(params[:mcomment],:body =>  @bodyUpdate)
        format.html { redirect_to @issue, notice: 'Comment was successfully updated.' }
        format.json {render :json => @comment.as_json(methods: [:userName,:hoursAgo,:body],
                                          except: [:created_at, :updated_at, :name]), status: :ok}
      else

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/blockerIssues.html.erb
<p id="notice"><%= notice %></p>


<div=class nav-header>
  <h1>Blocker Issues</h1> 
  <div class ="collapse navbar-collapse"> 
  <p class="navbar-text navbar-right"><%= link_to 'New Issue', new_issue_path, class:"btn btn-primary"%>
  </p>
  </div>
</div>

    <div>Filter by : 
    <%= link_to 'All', 'issues', class:"btn btn-primary"   %>
    <%= link_to ' Open', 'Opened', class:"btn btn-success" %>
    <%= link_to ' Closed', 'Closed', class:"btn btn-danger"  %>
    <%= link_to ' My Issues', 'mine', class:"btn btn-info" %>
    <%= link_to ' Watching', 'watching', class:"btn btn-warning"  %>
  </div>
<br>
<div> 
  <center> 
    <table class="table table-hover">
        <tr>
          <th><%= sortable "issue", "Title" %></th>
          <th><%= sortable "user", "Created By" %></th>
          <th><%= sortable "Category" %></th>
          <th><%= sortable "Priority" %></th>
          <th><%= sortable "open", "Status" %></th>
          <th style="color: #0066ff;">Votes</th>
          <th><%= sortable "Assignee", "Assigned To" %></th>
          <th><%= sortable "created_at", "Created" %></th>
          <th><%= sortable "updated_at", "Last Update" %></th>
          <th colspan="5"></th>
        </tr>
    
        <% @issues.each do |issue| %>
            <tr>
              <td><%=link_to issue.issue, issue %></td>
              <td><%= issue.user %></td>
              <td><%= link_to issue.category, issue.category %></td>
            <td><center><%= link_to issue.priority, issue.priority %></center></td>
              <td><%= link_to issue.getStatus, issue.getStatus %></td>
              <td><%= issue.get_upvotes.size-issue.get_downvotes.size %></td>
              <td><%= issue.assignee %></td>
              <td><%= time_ago_in_words(issue.created_at) %></td>
              <td><%= time_ago_in_words(issue.updated_at) %></td>
            <!--td><center><!--%= link_to 'Show', issue, class:"btn btn-primary" %--><!--/td-->
            <!--% if (issue.user == session[:user_id]) %-->
            <!--td><!--%= link_to 'Edit', edit_issue_path(issue), class:"btn btn-primary" %></td>
            <!--td><!--%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-primary" %></td>
            <!--%end%-->
            </tr>
        <% end %>
    </table>
    </center> 
</div>    
<br>

<!--%= link_to 'New Issue', new_issue_path, class:"btn btn-primary" >

app/views/issues/duplicateIssues.html.erb
<p id="notice"><%= notice %></p>


<div=class nav-header>
  <h1>Duplicated Issues</h1> 
  <div class ="collapse navbar-collapse"> 
  <p class="navbar-text navbar-right"><%= link_to 'New Issue', new_issue_path, class:"btn btn-primary"%>
  </p>
  </div>
</div>

  <div>Filter by : 
    <%= link_to 'All', 'issues', class:"btn btn-primary"   %>
    <%= link_to ' Open', 'Opened', class:"btn btn-success" %>
    <%= link_to ' On hold', 'On holded', class:"btn btn-success" %>
    <%= link_to ' Resolve', 'Resolved', class:"btn btn-success" %>
    <%= link_to ' Duplicate', 'Duplicated', class:"btn btn-success" %>
    <%= link_to ' Invalidate', 'Invalid', class:"btn btn-success" %>
    <%= link_to ' Wontfix', 'Wontfixed', class:"btn btn-success" %>
    <%= link_to ' Close', 'Closed', class:"btn btn-danger"  %>
    <%= link_to ' My Issues', 'mine', class:"btn btn-info" %>
    <%= link_to ' Watching', 'watching', class:"btn btn-warning"  %>
  </div>
<br>
<div> 
  <center> 
    <table class="table table-hover">
        <tr>
          <th><%= sortable "issue", "Title" %></th>
          <th><center><%= sortable "user", "Created By" %></center></th>
          <th><center><%= sortable "Category" %></center></th>
          <th><center><%= sortable "Priority" %></center></th>
          <th><center><%= sortable "open", "Status" %></center></th>
          <th style="color: #0066ff;"><center>Votes</center></th>
          <th><center><%= sortable "Assignee", "Assigned To" %></center></th>
          <th><center><%= sortable "created_at", "Created" %></center></th>
          <th><center><%= sortable "updated_at", "Last Update" %></center></th>
          <th colspan="5"></th>
        </tr>
    
        <% @issues.each do |issue| %>
          <tr>
            <td><%=link_to issue.issue, issue %></td>
            <td><center><%= issue.user %></center></td>
            <td><center><%= link_to issue.category, issue.category %></center></td>
            <td><center><%= link_to issue.priority, issue.priority %></center></td>
            <td><center><%= link_to issue.getStatus, issue.getStatus %></center></td>
            <td><center><%= issue.get_upvotes.size-issue.get_downvotes.size %></center></td>
            <td><center><%= issue.assignee %></center></td>
            <td><center><%= time_ago_in_words(issue.created_at) %></center></td>
            <td><center><%= time_ago_in_words(issue.updated_at) %></center></td>
            <!--td><center><!--%= link_to 'Show', issue, class:"btn btn-primary" %--><!--/td-->
            <!--% if (issue.user == session[:user_id]) %-->
            <!--td><!--%= link_to 'Edit', edit_issue_path(issue), class:"btn btn-primary" %></td>
            <!--td><!--%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-primary" %></td>
            <!--%end%-->
          </tr>
        <% end %>
    </table>
    </center> 
</div>    
<br>

<!--%= link_to 'New Issue', new_issue_path, class:"btn btn-primary" >

app/views/issues/edit.html.erb
<p>
<h1 style="display:inline">Editing Issue </h1>

<%= link_to 'Show', @issue , class:"btn-sm btn-primary" %> 

<% if @issue.isOpened()   %>
    <%= link_to 'Close Issue',  closeIssue_path(:id=>@issue.id), class:"btn-sm btn-warning" %>
<% end  %>

<% if !@issue.isOpened()  %>
    <%= link_to 'Open Issue',  openIssue_path(:id=>@issue.id), class:"btn-sm btn-success" %>
<% end  %>
</p>
<!--
 opened: <= debug @issue.open %>, <= @issue.isOpened() %>
-->
<%= render 'form', issue: @issue %>


<!-- FUNCIONA
< if @issue.isOpened() == true  %>
    <= link_to 'Close Issue',  closeIssue_path(:id=>@issue.id) %>
< end  %>

< if @issue.isClosed() == true %>
    <= link_to 'Open Issue',  openIssue_path(:id=>@issue.id) %>
< end  %>
% -->

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>
<br>

<div class="row">
  <div class="col-sm-8 well">
    <p >
      <strong>Issue: </strong>
      <%= @issue.issue %>
    </p>
    
    <p>
      <strong>Created:</strong>
      <%= @issue.created_at %>
    </p>

    <p>
      <strong>Last Update:</strong>
      <%= @issue.updated_at %>
    </p>
    
    
    <p>
      <strong>Description:</strong>
      <%= @issue.description %>
    </p>
    <br>
    <p>
      <strong>Attachment:</strong>
        <% if @issue.attachment? %>
          <a target="_blank" href="<%= @issue.attachment %>"> Ver archivo </a>
        <% else %>
          This Issue doesn't have an attachment
        <% end %>
    </p>
    
  </div>


  <div class="col-sm-4" >
    
    
    <div><%= link_to edit_issue_path(@issue), class: "edit", method: :put do%> <!-- Canviar el path -->
          <button type="button" class="btn btn-primary" aria-label="Left Align">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          </button>
          <% end %>
    <%= link_to 'Delete', @issue, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-primary" %>
    <%= link_to 'Back', issues_path, class:"btn btn-primary" %>

    <%= link_to 'Open Issue',  openIssue_path(:id=>@issue.id), class:"btn-sm btn-success" %>
    <%= link_to 'On hold Issue',  onHoldIssue_path(:id=>@issue.id), class:"btn-sm btn-primary" %>
    <%= link_to 'Resolve Issue',  resolveIssue_path(:id=>@issue.id), class:"btn-sm btn-primary" %>
    <%= link_to 'Duplicate Issue',  duplicateIssue_path(:id=>@issue.id), class:"btn-sm btn-primary" %>
    <%= link_to 'Invalidate Issue',  invalidateIssue_path(:id=>@issue.id), class:"btn-sm btn-primary" %>
    <%= link_to 'Wontfix Issue', wontfixIssue_path(:id=>@issue.id), class:"btn-sm btn-primary" %>
    <%= link_to 'Close Issue',  closeIssue_path(:id=>@issue.id), class:"btn-sm btn-warning" %>
    
    <!--% if @issue.isOpened()   %-->
      <!--%= link_to 'Close Issue',  closeIssue_path(:id=>@issue.id), class:"btn-sm btn-warning" %-->
    <!--% end  %-->

    <!--% if !@issue.isOpened()  %-->
      <!--%= link_to 'Open Issue',  openIssue_path(:id=>@issue.id), class:"btn-sm btn-success" %-->
    <!--% end  %-->
    </div>
    <br>
    
    <div class="well"> 
    
    <p>
    <strong>Created by : </strong>
      <%= @issue.user %>
    </p>

    <p>
    <strong>Assigned to : </strong>
      <%= @issue.assignee %>
    </p>
    
    <p>
    <strong>Category:</strong>
      <%= @issue.category %>
    </p>

    <p>
    <strong>Priority: </strong>
      <%= @issue.priority %>
    </p>
    
    <p>
    <strong>Status: </strong>
       <%= @issue.getStatus() %>

    </p>
    

    
    
    <p>
      <strong>Votes:</strong>
        <%= (@issue.get_upvotes.size-@issue.get_downvotes.size) %>
  
      <div class="vote circle" style="text-align:Left;">
        <%= link_to like_issue_path(@issue), class: "like", method: :put do%>
      <button type="button" class="btn btn-success" aria-label="Left Align">
        <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
        <span class="badge"><%=@issue.get_upvotes.size %></span>
      </button>
      <% end %>
    
      <%= link_to unlike_issue_path(@issue), class: "like", method: :put do%>
      <button type="button" class="btn btn-danger" aria-label="Left Align">
        <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>
        <span class="badge"><%=@issue.get_downvotes.size %></span>
      </button>
      <% end %>
      </div>
    </p>
    
    <p>
        <% if current_user.watching?(@issue) %>
          <%= link_to unwatch_issue_path(@issue), class: "watch", method: :put do%> <!-- Canviar el path -->
          <button type="button" class="btn btn-primary" aria-label="Left Align">
            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
          </button>
          <% end %>
          <strong>Watching</strong>
        <% else %>
          
          <%= link_to watch_issue_path(@issue), class: "watch", method: :put do%> <!-- Canviar el path -->
          <button type="button" class="btn btn-warning" aria-label="Left Align">
            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
          </button>
          <% end %>
          <strong>Not watching</strong>
        <% end %>
      </div>
      </div>
    </p>
    
    </div>
  </div>


</div>
<hr class="divider">

<div class="row">
  
</div>











  
<br>
<!--<  @editingComment = -1 %>
NumEditing:
  <= @editingComment %>-->
<h2> <%= @issue.comments.count %> Comments</h2>
<ol class="pageCommentBody">
  
  
  <% @issue.comments.each do |comment| %>
  <div class="well well-lg .well"> 
    <li class="list">
      <div class="subtitle">
        <p>
        <td><%= 'Comment by: ' %> <strong><%= comment.userName  %></strong> </td> 
        <td> | <%= distance_of_time_in_words_to_now(comment.created_at) %></td>
        <td><%= ' ago ' %></td>
          <% if(comment.getUserId == session[:user_id]) %>
            <td>| <b><%= link_to 'Destroy' , destroycomment_path(:id=>@issue.id, :comment=>comment),data: { confirm: 'Are you sure?' } , class:"btn-xs btn-danger"%></b></td>
            <!--<td>| <b><= link_to 'Edit' , editcomment_path(:id=>@issue.id, :comment=>comment), class:"btn-xs btn-warning" %></b></td> -->
            <td>| <b><%= link_to 'Edit' , class:"btn-xs btn-warning", :editingComment=> comment.id %></b></td>
          <% end %>
          </p>
      </div>

      <div >
        <td><%= comment.body %></td>
        <% if(comment.getUserId == session[:user_id])  %>
        <td> <%=  render  :partial => "comments/formEditComment", :locals => { :mcomment=> comment } %></td>
        <% end %>
      </div>
    </li>
    </div>
    <br>
  <% end %>
</ol> 
<br>
  <!--%= render @issue.comments %-->
  
  
  <h2> Add a Comment: </h2>
  <%= render 'comments/form' %>