config/routes.rb
Rails.application.routes.draw do

  resources :comments

  get 'sessions/create'

  get 'sessions/destroy'
  get '/issues/mine', to: 'issues#mine'
  get '/issues/watching', to: 'issues#watching'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]


  root 'home#index'

  resources :issues do 
    resources :comments
    get :watchers
    member do
      put "like" => "issues#upvote"
      put "unlike" => "issues#downvote"
      put "watch" => "issues#watch"
      put "unwatch" => "issues#unwatch"
      put "edit" => "issues#edit"
    end
  end
  resources :users do
    get :watching
  end
  
  get '/issues/:id/attachment', to: 'issues#showAttachment'
  post '/issues/:id/attachment', to: 'issues#createAttachment'
  get 'Opened', to: 'issues#openIssues'
  get 'On holded', to: 'issues#onHoldIssues'  
  get 'Resolved', to: 'issues#resolveIssues'
  get 'Duplicated', to: 'issues#duplicateIssues'
  get 'Invalid', to: 'issues#invalidateIssues'
  get 'Wontfixed', to: 'issues#wontfixIssues'
  get 'Closed', to: 'issues#closeIssues'
  get 'Task', to: 'issues#taskIssues'
  get 'Bug', to: 'issues#bugIssues'
  get 'Enhancement', to: 'issues#enhancementIssues'
  get 'Proposal', to: 'issues#proposalIssues'
  get 'Trivial', to: 'issues#trivialIssues'
  get 'Minor', to: 'issues#minorIssues'
  get 'Major', to: 'issues#majorIssues'
  get 'Critical', to: 'issues#criticalIssues'
  get 'Blocker', to: 'issues#blockerIssues'
  
  post 'editcomment', controller: "issues", action: "editcomment"
  get 'destroycomment', controller: "issues" , action: "destroycomment"
  get 'openIssue', controller: "issues", action: "openIssue"
  get 'onHoldIssue', controller: "issues", action: "onHoldIssue"
  get 'resolveIssue', controller: "issues", action: "resolveIssue"
  get 'duplicateIssue', controller: "issues", action: "duplicateIssue"
  get 'invalidateIssue', controller: "issues", action: "invalidateIssue"
  get 'wontfixIssue', controller: "issues", action: "wontfixIssue"
  get 'closeIssue', controller: "issues", action: "closeIssue"
  get 'isOpen', controller: "issues", action: "isOpen"
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :issues, dependent: :destroy 
  has_many :comments, dependent: :destroy 
  has_many :active_watches, class_name: "WatchRelationship", foreign_key: "watcher_id", dependent: :destroy
  has_many :watching, through: :active_watches, source: :watched
  acts_as_voter

  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
  
  #Watch an issue
  
  def watch(other)
    active_watches.create(watched_id: other)
  end
  
  def unwatch(other)
    active_watches.find_by(watched_id: other).destroy
  end
  
  def watching?(other)
    watching.include?(other)
  end
  
  def getId
    self.uid
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    
    respond_to do |format|
      format.html {}
      format.json {
        render :json => @users.as_json(methods: [:hoursAgo, :userURL], except: [:token, :secret, :provider, :auth_token, :updated_at, :uid, :created_at])
      }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    respond_to do |format|
      format.html {}
      format.json {
        if @user == authenticate
          render :json => @user.as_json(methods: [:hoursAgo, :userURL], except: [:provider,:secret,:token,:updated_at,:created_at])
        else
          render :json => @user.as_json(methods: [:hoursAgo, :userURL], except: [:token,:provider,:secret,:auth_token,:updated_at,:created_at])
        end
      }
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
    
    
    
    
    def authenticate
      authenticate_or_request_with_http_token do |token, options|
        return User.find_by(auth_token: token)
      end
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>
  
  <div class="field">
    <%= form.label :token %>
    <%= form.text_field :token, id: :oauth_token %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.oauth_token %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>