config/routes.rb
Rails.application.routes.draw do

  resources :comments

  get 'sessions/create'

  get 'sessions/destroy'
  get '/issues/mine', to: 'issues#mine'
  get '/issues/watching', to: 'issues#watching'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]


  root 'home#index'

  resources :issues do 
    resources :comments
    get :watchers
    member do
      put "like" => "issues#upvote"
      put "unlike" => "issues#downvote"
      put "watch" => "issues#watch"
      put "unwatch" => "issues#unwatch"
      put "edit" => "issues#edit"
    end
  end
  resources :users do
    get :watching
  end
  
  get '/issues/:id/attachment', to: 'issues#showAttachment'
  post '/issues/:id/attachment', to: 'issues#createAttachment'
  get 'Opened', to: 'issues#openIssues'
  get 'On holded', to: 'issues#onHoldIssues'  
  get 'Resolved', to: 'issues#resolveIssues'
  get 'Duplicated', to: 'issues#duplicateIssues'
  get 'Invalid', to: 'issues#invalidateIssues'
  get 'Wontfixed', to: 'issues#wontfixIssues'
  get 'Closed', to: 'issues#closeIssues'
  get 'Task', to: 'issues#taskIssues'
  get 'Bug', to: 'issues#bugIssues'
  get 'Enhancement', to: 'issues#enhancementIssues'
  get 'Proposal', to: 'issues#proposalIssues'
  get 'Trivial', to: 'issues#trivialIssues'
  get 'Minor', to: 'issues#minorIssues'
  get 'Major', to: 'issues#majorIssues'
  get 'Critical', to: 'issues#criticalIssues'
  get 'Blocker', to: 'issues#blockerIssues'
  
  post 'editcomment', controller: "issues", action: "editcomment"
  get 'destroycomment', controller: "issues" , action: "destroycomment"
  get 'openIssue', controller: "issues", action: "openIssue"
  get 'onHoldIssue', controller: "issues", action: "onHoldIssue"
  get 'resolveIssue', controller: "issues", action: "resolveIssue"
  get 'duplicateIssue', controller: "issues", action: "duplicateIssue"
  get 'invalidateIssue', controller: "issues", action: "invalidateIssue"
  get 'wontfixIssue', controller: "issues", action: "wontfixIssue"
  get 'closeIssue', controller: "issues", action: "closeIssue"
  get 'isOpen', controller: "issues", action: "isOpen"
  
end

app/helpers/layout_helper.rb
module LayoutHelper
    def time_ago_in_words(from_time, include_seconds_or_options = {})
        distance_of_time_in_words(from_time, Time.now, include_seconds_or_options)
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
 
 </head>
  <body>
    <div>
      <% if current_user %>
       
        <nav class="navbar navbar-inverse justify-content-end bg-inverse">

            <font color="white">Signed in as <strong><%= current_user.name %></strong>!
            <%= link_to "Sign out", signout_path, id: "sign_out" %></font>
        </nav>
      <% else %>
      <% end %>
    </div>
    <div>
    <%= yield %>
    </div>
  </body>
</html>